/* Copyright (c) Microsoft Corporation. All rights reserved.
   Licensed under the MIT License. */

// This file defines the mapping from the Avnet Azure Sphere Starter Kit Rev-1 board to the
// hardware devices required for the Avnet BBQ Monitor example
// https://docs.microsoft.com/en-us/azure-sphere/app-development/manage-hardware-dependencies
// to enable apps to work across multiple hardware variants.

// This file is autogenerated from ../../bbq_monitor.json.  Do not edit it directly.

#pragma once
#include "avnet_mt3620_sk_rev2.h"

// Install the Buzz CLICK into CLICK socket #2 (PWM)
#define PWM_CLICK_CONTROLLER AVNET_MT3620_SK_PWM_CONTROLLER0

// Avnet Starter Kit LED RED Channel.
#define RGBLED_RED AVNET_MT3620_SK_USER_LED_RED

// Avnet Starter Kit LED  GREEN Channel.
#define RGBLED_GREEN AVNET_MT3620_SK_USER_LED_GREEN

// Avnet Starter Kit LED  BLUE Channel.
#define RGBLED_BLUE AVNET_MT3620_SK_USER_LED_BLUE

// Avnet Starter Kit App LED
#define UPDATE_PENDING_LED AVNET_MT3620_SK_APP_STATUS_LED_YELLOW

// SSD 1306 OLED installed on the Avnet Starter Kit.
#define OLED_I2C AVNET_MT3620_SK_ISU2_I2C

// Avnet Starter Kit User Button A.
#define BUTTON_1 AVNET_MT3620_SK_USER_BUTTON_A

// Avnet Starter Kit User Button B.
#define BUTTON_2 AVNET_MT3620_SK_USER_BUTTON_B

